### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by soramico** [soramico/furima-40946#21]
#URL
https://furima-40946.onrender.com/

**Comment by OhyaYouki** [comment]
ご提出ありがとうございます!! 

上記のURLにアクセスしたところエラーが発生しページを開くことができませんでした。
お手数ですが今一度挙動を確認いただき、再度挙動確認依頼のご提出をお願いいたします。

※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by soramico** [comment]
ご確認いただきありがとうございます！
メンターさんに相談し、確認いたしましたのでよろしくお願いいたします。

**Comment by OhyaYouki** [comment]
ご提出ありがとうございます!! 
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします!

[修正依頼箇所]

**商品出品機能の確認**
- [x] **商品の状態は、`「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目`が表示されること（--- は初期値として設定すること）**
現状は「未使用品に近い」とございました。細かい点ですが「未使用に近い」と修正をお願いいたします。

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
トップページから商品出品ページに遷移するとjavascriptが反応していないようです。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします!
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by soramico** [comment]
レビューありがとうございます。
ご指摘いただいた２点、修正完了いたしましたのでご確認お願いいたします。

**Comment by OhyaYouki** [comment]
最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
